# Starting with R

<span style="font-size: 22px; font-weight: bold; color: var(--purple);">Welcome to the Course!</span>

## Overview

Installing R and opening files

**In this session you will learn\:**

1. What is R?
2. How to install R
3. Where to get help


### What is R?

For network analysis, you need two different bits of software, R and RStudio. R is a programming language that you will write code in and R Studio is an Integrated Development Environment (IDE) which makes working with R easier.

### How To Install Base R

Install base R from [https://cran.rstudio.com/](https://cran.rstudio.com/){target="_blank"}. Choose the download link for your operating system (Linux, Mac OS X, or Windows).

### How To Install R Studio

Go to [https://rstudio.com](https://rstudio.com){target="_blank"} and download the RStudio Desktop (Open Source License) version for your operating system under the list titled **Installers for Supported Platforms.**

If you are using a Mac, please install [XQuartz](https://www.xquartz.org/){target="_blank"}



### Quiz

<span style="font-size: 22px; font-weight: bold; color: var(--blue);">Quickfire Questions</span>

We have put questions throughout to help you test your knowledge. When you type in or choose the correct answer, the dashed box will change color and become solid green.

- From the following options, how do you get R for this course? `r mcq(c(answer = "Installing Base R & R Studio", "Installing R Studio", "Installing Base R"))`  

`r hide("Explain This Answer!")`
```{block}
R is the basic package. R Studio is an add-on that make R much easier to use.
```
`r unhide()`  

## Where to Get Help

Learning R can take time. Please do not feel that you have to grasp everything right away and it is totally ok to copy and paste.

### Google

"Never commit to memory what can be easily looked up in books" 

Often people simply google what they want to achieve in R. For example, in preparing this tutorial I googled "how to run a linear mixed effects model in R" and found the following [helpful tutorial](https://ourcodingclub.github.io/2017/03/15/mixed-models.html){target="_blank"} This is just one of many examples of resources that are available.

### Stackoverflow

[Stackoverflow](https://stackoverflow.com) is a website where you can ask for help on bits of coding that you are struggling with. You can search for commonly asked questions and responses.
